/**
 * Enum representing the possible statuses of a Stripe PaymentIntent.
 */
export enum StripePaymentIntentStatus {
  Canceled = 'canceled',
  Processing = 'processing',
  RequiresAction = 'requires_action',
  RequiresCapture = 'requires_capture',
  RequiresConfirmation = 'requires_confirmation',
  RequiresPaymentMethod = 'requires_payment_method',
  Succeeded = 'succeeded'
}

export enum StripeRefundStatus {
  Pending = 'pending',
  RequiresAction = 'requires_action',
  Succeeded = 'succeeded',
  Failed = 'failed',
  Canceled = 'canceled'
}

export enum StripeErrorCodes {
  BalanceInsufficient = 'balance_insufficient',
  AccountInvalid = 'account_invalid',
  AccountNumberInvalid = 'account_number_invalid',
  AmountTooLarge = 'amount_too_large',
  AmountTooSmall = 'amount_too_small',
  ApiKeyExpired = 'api_key_expired',
  AuthenticationRequired = 'authentication_required',
  BankAccountExists = 'bank_account_exists',
  BankAccountUnusable = 'bank_account_unusable',
  CardDeclined = 'card_declined',
  ChargeAlreadyCaptured = 'charge_already_captured',
  ChargeAlreadyRefunded = 'charge_already_refunded',
  ChargeDisputed = 'charge_disputed',
  CountryUnsupported = 'country_unsupported',
  CouponExpired = 'coupon_expired',
  CustomerMaxSubscriptions = 'customer_max_subscriptions',
  EmailInvalid = 'email_invalid',
  ExpiredCard = 'expired_card',
  IncorrectAddress = 'incorrect_address',
  IncorrectCvc = 'incorrect_cvc',
  IncorrectNumber = 'incorrect_number',
  IncorrectZip = 'incorrect_zip',
  InstantPayoutsUnsupported = 'instant_payouts_unsupported',
  InvalidCardType = 'invalid_card_type',
  InvalidChargeAmount = 'invalid_charge_amount',
  InvalidCvc = 'invalid_cvc',
  InvalidExpiryMonth = 'invalid_expiry_month',
  InvalidExpiryYear = 'invalid_expiry_year',
  InvalidNumber = 'invalid_number',
  InvalidSourceUsage = 'invalid_source_usage',
  InvoiceNoCustomerLineItems = 'invoice_no_customer_line_items',
  InvoiceNoSubscriptionLineItems = 'invoice_no_subscription_line_items',
  InvoicePending = 'invoice_pending',
  PaymentMethodUnactivated = 'payment_method_unactivated',
  PaymentMethodUnexpectedState = 'payment_method_unexpected_state',
  PayoutsNotAllowed = 'payouts_not_allowed',
  ProcessingError = 'processing_error',
  ProductInactive = 'product_inactive',
  RateLimit = 'rate_limit',
  ResourceMissing = 'resource_missing',
  RoutingNumberInvalid = 'routing_number_invalid',
  SecretKeyRequired = 'secret_key_required',
  SepaUnsupportedAccount = 'sepa_unsupported_account',
  ShippingCalculationFailed = 'shipping_calculation_failed',
  SkuInactive = 'sku_inactive',
  StateUnsupported = 'state_unsupported',
  TaxIdInvalid = 'tax_id_invalid',
  TokenAlreadyUsed = 'token_already_used',
  TokenInUse = 'token_in_use'
}

export enum StripeDeclineCodes {
  InsufficientFunds = 'insufficient_funds',
  LostCard = 'lost_card',
  StolenCard = 'stolen_card',
  ExpiredCard = 'expired_card',
  IncorrectCvc = 'incorrect_cvc',
  ProcessingError = 'processing_error',
  IncorrectNumber = 'incorrect_number',
  IncorrectZip = 'incorrect_zip',
  IncorrectAddress = 'incorrect_address',
  CardDeclined = 'card_declined',
  CallIssuer = 'call_issuer',
  PickupCard = 'pickup_card',
  WithdrawalCountLimitExceeded = 'withdrawal_count_limit_exceeded',
  CurrencyNotSupported = 'currency_not_supported',
  DuplicateTransaction = 'duplicate_transaction',
  FraudulentDecline = 'fraudulent',
  DoNotHonor = 'do_not_honor',
  GenericDecline = 'generic_decline',
  NotAllowed = 'not_allowed',
  TransactionNotAllowed = 'transaction_not_allowed',
  RestrictedCard = 'restricted_card',
  SecurityViolation = 'security_violation',
  InvalidAmount = 'invalid_amount',
  InvalidCvc = 'invalid_cvc',
  InvalidExpiryDate = 'invalid_expiry_date',
  InvalidNumber = 'invalid_number',
  InvalidAccount = 'invalid_account',
  TryAgainLater = 'try_again_later'
}
