version: '3.8'
services:
  db:
    container_name: template-project-db
    image: postgres:13
    environment:
      POSTGRES_DATABASE: db
      POSTGRES_USER: template-project
      POSTGRES_PASSWORD: template-project
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '3006:5432'
    env_file: .env.local
    networks:
      - template-project-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U template-project']
      interval: 1s
      timeout: 5s
      retries: 5

  template-project-api:
    container_name: template-project-api
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3005:3005'
    env_file: .env.local
    networks:
      - template-project-network
    command: >
      sh -c "
        npx prisma generate &&
        if [ \"$DB_RESET\" = \"true\" ]; then
          npx prisma migrate reset --force 
          npx prisma migrate dev
        else
          echo 'deploy'
          npx prisma migrate deploy 
        fi &&
        npm run seed-database &&
        npm run seed-database:dev &&
        npm run dev-only
      "

networks:
  template-project-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
