# Use an official Node.js runtime as a parent image
FROM node:20

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Generate Prisma client
# RUN npx prisma generate

COPY . .

# Expose the port that the app runs on
EXPOSE 3005

# Force copy package.json
COPY --chown=node:node package.json ./


# Start the app with Vite for hot-reloading
CMD ["npm", "run", "dev-only"]